include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    missing_required_param: error
    missing_return: error
  plugins:
    - custom_lint

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    no_runtimeType_toString: true
